spring:
  application:
    name: model-mapper
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME} #root
    url: ${DATABASE_URL} #jdbc:mysql://localhost:3306/sla-cms
    password: ${DATABASE_PASSWORD} #MySql@123
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} #update/none
    show-sql: false